/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrizeRouteImport } from './routes/prize'
import { Route as PressReleaseRouteImport } from './routes/press-release'
import { Route as MagazineRouteImport } from './routes/magazine'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PrizeRoute = PrizeRouteImport.update({
  id: '/prize',
  path: '/prize',
  getParentRoute: () => rootRouteImport,
} as any)
const PressReleaseRoute = PressReleaseRouteImport.update({
  id: '/press-release',
  path: '/press-release',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazineRoute = MagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exam': typeof ExamRoute
  '/gallery': typeof GalleryRoute
  '/magazine': typeof MagazineRoute
  '/press-release': typeof PressReleaseRoute
  '/prize': typeof PrizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exam': typeof ExamRoute
  '/gallery': typeof GalleryRoute
  '/magazine': typeof MagazineRoute
  '/press-release': typeof PressReleaseRoute
  '/prize': typeof PrizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/exam': typeof ExamRoute
  '/gallery': typeof GalleryRoute
  '/magazine': typeof MagazineRoute
  '/press-release': typeof PressReleaseRoute
  '/prize': typeof PrizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/exam'
    | '/gallery'
    | '/magazine'
    | '/press-release'
    | '/prize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/exam'
    | '/gallery'
    | '/magazine'
    | '/press-release'
    | '/prize'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/exam'
    | '/gallery'
    | '/magazine'
    | '/press-release'
    | '/prize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExamRoute: typeof ExamRoute
  GalleryRoute: typeof GalleryRoute
  MagazineRoute: typeof MagazineRoute
  PressReleaseRoute: typeof PressReleaseRoute
  PrizeRoute: typeof PrizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prize': {
      id: '/prize'
      path: '/prize'
      fullPath: '/prize'
      preLoaderRoute: typeof PrizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-release': {
      id: '/press-release'
      path: '/press-release'
      fullPath: '/press-release'
      preLoaderRoute: typeof PressReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazine': {
      id: '/magazine'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof MagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExamRoute: ExamRoute,
  GalleryRoute: GalleryRoute,
  MagazineRoute: MagazineRoute,
  PressReleaseRoute: PressReleaseRoute,
  PrizeRoute: PrizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
